# Generated by Django 5.0a1 on 2025-03-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='address',
            new_name='email',
        ),
    ]
